### ISSUE TITLE
dies if "q" is typed to quit

### ISSUE THREAD

**Issue by nkh** [nige123/jmp.nigelhamilton.com#10]
34 ~/Downloads jmp ls
Unhandled exception in code scheduled on thread 7
A react block:
  in code  at /home/nadim/nadim/devel/repositories/rakudo/install/share/perl6/site/sources/F8D16F94A23B6A83F4D0687159D31DC9C099B12C (Terminal::Print::DecodedInput) line 150

Died because of the exception:
    No such method 'done' for invocant of type 'Supply'. Did you mean any of these?
        clone
        do
        does
        none

      in block  at /home/nadim/nadim/devel/repositories/rakudo/install/share/perl6/site/sources/F8D16F94A23B6A83F4D0687159D31DC9C099B12C (Terminal::Print::DecodedInput) line 241
      in block  at /home/nadim/nadim/devel/repositories/rakudo/install/share/perl6/site/sources/217FBEBE8FFB31DAC17F3EDD394D8A8DFBB342C0 (JMP::UI) line 39
      in block  at /home/nadim/nadim/devel/repositories/rakudo/install/share/perl6/site/sources/F8D16F94A23B6A83F4D0687159D31DC9C099B12C (Terminal::Print::DecodedInput) line 189
      in block  at /home/nadim/nadim/devel/repositories/rakudo/install/share/perl6/site/sources/F8D16F94A23B6A83F4D0687159D31DC9C099B12C (Terminal::Print::DecodedInput) line 187
      in block  at /home/nadim/nadim/devel/repositories/rakudo/install/share/perl6/site/sources/779A552D6640C06952A77740DD3CBBA75F3A6277 (Terminal::Print::RawInput) line 35

**Comment by nige123** [comment]
HI Nadim,

Thanks for the bug report - I think this error won't happen with the latest version of Perl 6.

Cheers

NIge

**Comment by nkh** [comment]
Hi, I compile rakudo 2 hours ago. It doesn't matter if the key is 'q' or 'x' as display in the "bar", the error occurs anyway.

**Comment by nige123** [comment]
Could you please run this and let me know the output?

shell> perl6 -v

**Comment by nkh** [comment]
I build my own, a few days old.

This is Rakudo version 2018.11-82-ge7b61aff7 built on MoarVM version 2018.11-39-g987269ea9
implementing Perl 6.d.

**Comment by nige123** [comment]
I was unable to replicate this bug.
